# Generated by Django 5.2.9 on 2026-01-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_financeiro'),
        ('alunos', '0002_aluno_responsavel_matricula'),
    ]

    operations = [
    ]
